'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { useState } from 'react';
import { ThemeProvider, CssBaseline } from '@mui/material';
import { lightTheme, darkTheme } from './theme/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [isDark, setIsDark] = useState(false);
  const switchTheme = () => setIsDark((init) => !init);

  return (
    <html lang="en">
      <ThemeProvider theme={isDark ? darkTheme : lightTheme}>
        <CssBaseline>
          <body className={inter.className}>{children}</body>
        </CssBaseline>
      </ThemeProvider>
    </html>
  );
}
